<?php return array (
  'about' => true,
  'comments' => true,
  'contribute' => true,
  'documentation' => true,
  'edit-profile' => true,
  'feedback' => true,
  'learn' => true,
  'logout' => true,
  'menu-toggle' => true,
  'my-account' => true,
  'new-content' => true,
  'new-link' => true,
  'new-media' => true,
  'new-page' => true,
  'new-post' => true,
  'new-user' => true,
  'site-name' => true,
  'support-forums' => true,
  'top-secondary' => true,
  'user-actions' => true,
  'user-info' => true,
  'view-site' => true,
  'wp-logo' => true,
  'wp-logo-external' => true,
  'wporg' => true,
);